module.exports = {
  CREATE_ITEM: "create_item",
  CREATE_CART: "create_cart",
  READ: "read",
  UPDATE_PASS: "update_pass",
  UPDATE_CART: "update_cart",
  UPDATE_ITEM: "update_item",
  DELETE_ITEM: "delete_item",
  DELETE_CART: "delete_cart",
  CREATE_ORDER: "create_order",
  PAY_TRANSACTION: "pay_transaction",
  VERIFY_PAYMENT: "verify_payment",
  UPDATE_ORDER_STATUS: "update_order_status",
  DONE_ORDER: "done_order",
};
